# Generated by Django 6.0.7 on 2026-07-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Upload the main photo for this room. A placeholder is shown until one is added.', null=True, upload_to='rooms/'),
        ),
    ]
