# Generated by Django 6.0.7 on 2026-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabana', '0002_alter_room_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='e.g. 5.0 — shown as a star rating badge.', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_review_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of Google reviews backing the rating above.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(blank=True, help_text='Short description shown under the tagline on the homepage hero.'),
        ),
    ]
