# Generated by Django 6.0.7 on 2026-07-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabana', '0003_sitesettings_google_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='show_on_amenities_page',
            field=models.BooleanField(default=True, help_text="Uncheck for room-only features (e.g. 'Electric Kettle') so they don't clutter the property-wide Facilities & Amenities page."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='A Peaceful Hillside Retreat', max_length=200),
        ),
    ]
